### ISSUE TITLE
bebot.link registration failed

### ISSUE THREAD

**Issue by flesage-000** [J-Soft/BeBot#36]
Hello,

This isn't an issue, but I don't know how else to report it...

Registration on the bebot.link site seems to bug.

This tells me:
"Sorry, but users under the age of 0 are not allowed to register on this forum."

But there is no form to fill in the age...

Thx.

**Comment by bitnykk** [comment]
Thanks, you're right, to avoid spambots we had to raise level to an insane level, now fixed to allow at least user to register (but still requiring admin validation for sanity). Therefore closing issue.
